#!/bin/bash
#
# Copyright 2025 Elyra Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script generates Typescript declarations files from the JSON schemas
# contained in this repo. It does this by:
# 1. Copying all schemas to the ../schemas directory
# 2. Changing any references to child schemas in this form:
#       "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/parameters/parametersets-v3-schema.json#/definitions/paramset_ref"
#     to look like this:
#       "$ref": "./parametersets-v3-schema.json#/definitions/paramset_ref"
#     This makes the schemas like pipeline-flow-v3-schema.json have correct
#     references to its child schemas like parametersets-v3-schema.json.
# 3. Runs the json2ts utility command on each of the top level schemas to
#    generate the typescript declaration files.
#

set -e

WORKING_DIR="$PWD"

echo "Generating Typescript declarations."

# Replaces the lines in the file beginning with "$ref"
replace_string_in_file() {
	local file_path="$1"
	local url="$2"

	local old_string="\"\$ref\": \"https:\/\/api.dataplatform.ibm.com\/schemas\/common-pipeline\/"$url"\/"
	local new_string="\"\$ref\": \".\/"

	sed -i ''  "s/$old_string/$new_string/g" "$file_path"
}

# Call the replace string for each of the types of child schema
replace_string_schema() {
	local file=$1
	replace_string_in_file "$file" "datarecord-metadata"
	replace_string_in_file "$file" "pipeline-flow"
	replace_string_in_file "$file" "parameters"
	replace_string_in_file "$file" "pipeline-connection"
}

# Make sure we have an empty ../schemas directory and change to it

rm -rf ../schemas
mkdir ../schemas
cd ../schemas

# Copy all JSON schemas into the ../schemas directory

cp ../common-canvas/canvas-info/canvas-info-v3-schema.json .
cp ../common-canvas/palette/palette-v3-schema.json .

cp ../common-pipeline/datarecord-metadata/datarecord-metadata-v3-schema.json .
cp ../common-pipeline/parameters/parameters-v3-schema.json .
cp ../common-pipeline/parameters/parametersets-v3-schema.json .
cp ../common-pipeline/pipeline-connection/pipeline-connection-v3-schema.json .
cp ../common-pipeline/pipeline-flow/pipeline-flow-ui-v3-schema.json .
cp ../common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json .

# Replace the "ref": "http://...  references to become "ref": "./...

replace_string_schema "canvas-info-v3-schema.json"
replace_string_schema "pipeline-flow-v3-schema.json"

replace_string_schema "canvas-info-v3-schema.json"
replace_string_schema "palette-v3-schema.json"
replace_string_schema "datarecord-metadata-v3-schema.json"
replace_string_schema "parameters-v3-schema.json"
replace_string_schema "parametersets-v3-schema.json"
replace_string_schema "pipeline-connection-v3-schema.json"
replace_string_schema "pipeline-flow-ui-v3-schema.json"
replace_string_schema "pipeline-flow-v3-schema.json"

# Create a prologue to use for our TS declaration files
prologue="
/*
 * Copyright 2025 Elyra Authors
 *
 * Licensed under the Apache License, Version 2.0 (the \"License\");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an \"AS IS\" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the ../script/generateTS.sh script to regenerate all TS files.
 */
/* eslint-disable */
"

# Makes sure we have an empty  ../types directory
rm -rf ../types
mkdir ../types

# Run the json2ts utilities for the top level schemas

npx json2ts --bannerComment "$prologue" canvas-info-v3-schema.json ../types/canvas-info-v3.ts
npx json2ts --bannerComment "$prologue" pipeline-flow-v3-schema.json ../types/pipeline-flow-v3.ts
npx json2ts --bannerComment "$prologue" palette-v3-schema.json ../types/palette-v3.ts

cd $WORKING_DIR

echo "TS declarations generated successfully"
